### ISSUE TITLE
document.documentElement.clientWidth vs window.innerWidth

### ISSUE THREAD

**Issue by rmetzler** [ten1seven/jRespond#1]
On Google Chrome 20.0 for OSX `window.innerWidth` seems to return the width including scrollbar on the right side and `document.documentElement.clientWidth` excluding the scrollbar.

I think `document.documentElement.clientWidth` should be the value returned by the `winWidth()` function. I understand that these values differ from browser to browser.

**Comment by valuka** [comment]
+1 @charlietoleary 

I also use document.documentElement.clientWidth in favor of window.innerWidth to avoid potential pinch zoom issues and it works great.

**Comment by ten1seven** [comment]
Thanks for these comments! I'm going to look into this and give jRespond some attention in the next week or two.
