### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by jmagnusson** [ten1seven/jRespond#16]
It would be nice if jRespond was available as a Bower package :+1:

**Comment by simonseddon** [comment]
+1

**Comment by SuggeElson** [comment]
+2 :)

**Comment by hirnschmalz** [comment]
Hi there,

Since there did not happened too much in this repository I created a fork which does nothing else than add a bower configuration.
You can install jRespond via bower with

```BASH
bower install jrespond-bower
```

**Comment by ten1seven** [comment]
Hi @hirnschmalz, I've been having trouble with Github's notifications not letting me know about new issue and pull requests on jRespond. Thanks for adding Bower integration!
