### ISSUE TITLE
Add Version

### ISSUE THREAD

**Issue by andremleblanc** [ten1seven/jRespond#21]
Hello, trying to install this library with RailsAssets. It looks like you need to add versioning to the repo for it to work.

https://rails-assets.org/components/new
```
jRespond has no versions defined. Please create an issue in component's repository.
```

**Comment by ten1seven** [comment]
Thanks Andre, I'll look into it.

**Comment by ten1seven** [comment]
Just added a release and tested it with https://rails-assets.org/components/new.
