### ISSUE TITLE
compare to cssobj

### ISSUE THREAD

**Issue by futurist** [ten1seven/jRespond#24]
This lib https://github.com/cssobj/cssobj/ also do responsive for old browsers based on JS Object.

How this lib compared to [cssobj](https://github.com/cssobj/cssobj/) ?

**Comment by ten1seven** [comment]
jRespond is purely related to detecting changes in browser size so you can set functions to fire when the screen width changes (like media queries for javascript). I'm not familiar with cssobj but it appears to do quite a bit more.

If you're just looking for ways to use media queries in javascript, I'd recommend looking at the native matchMedia: https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia
