### ISSUE TITLE
which cases that document.body.clientWidth equal document.documentElement.clientWidth

### ISSUE THREAD

**Issue by ay00ya** [ten1seven/jRespond#26]
I need to know the difference between 
document.body.clientWidth and document.documentElement.clientWidth
and what is the different cases that make two values equal ?

**Comment by ten1seven** [comment]
Hi @ay00ya,

These checks for `body` versus `documentElement` are specific to very old versions of Internet Explorer and generally don't apply to modern browsers. 

I would recommend looking into [`window.matchMedia()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) instead, as jRespond was written to fill the same need before `window.matchMedia()` had broad support ([now it does](https://caniuse.com/#feat=matchmedia)).
